// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phsrtnyzbclobuanhnnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoc3J0bnl6YmNsb2J1YW5obm5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODczMzcsImV4cCI6MjA2NTQ2MzMzN30.lmwz1Nc4HQOXbdsfMadaBPRvGVPSoeSuKj5tJvWQg9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);